package luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 12:53:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajaTest {



  // Generated by ComTest BEGIN
  /** testLisaa20 */
  @Test
  public void testLisaa20() {    // Kayttaja: 20
    Kayttaja kayttajaX = new Kayttaja(); 
    Pvm paiva1 = new Pvm(); 
    Pvm paiva2=new Pvm(1,1,1); 
    paiva1.rekisteroi(); 
    paiva2.rekisteroi(); 
    assertEquals("From: Kayttaja line: 26", 0, kayttajaX.getEriPaivat()); 
    kayttajaX.lisaa(paiva1); 
    assertEquals("From: Kayttaja line: 28", 1, kayttajaX.getEriPaivat()); 
    kayttajaX.lisaa(paiva2); 
    assertEquals("From: Kayttaja line: 30", 2, kayttajaX.getEriPaivat()); 
    assertEquals("From: Kayttaja line: 31", paiva1, kayttajaX.annaPvm(0)); 
    assertEquals("From: Kayttaja line: 32", paiva2, kayttajaX.annaPvm(1)); 
    int id1 = paiva1.getTunnusNro(); 
    int id2 = paiva2.getTunnusNro(); 
    Urheilu sali1 = new Urheilu(id1); 
    Urheilu sali2 = new Urheilu(id2); 
    sali1.taytaTiedot(id1); 
    sali2.taytaTiedot(id2); 
    kayttajaX.lisaa(sali1); 
    kayttajaX.lisaa(sali2); 
    assertEquals("From: Kayttaja line: 41", true, kayttajaX.annaUrheilut(paiva1).contains(sali1)); 
    assertEquals("From: Kayttaja line: 42", false, kayttajaX.annaUrheilut(paiva2).contains(sali1)); 
  } // Generated by ComTest END
}