package luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 13:46:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LajitTest {



  // Generated by ComTest BEGIN
  /** testLisaa20 */
  @Test
  public void testLisaa20() {    // Lajit: 20
    Lajit lajitX = new Lajit(); 
    Laji lenkki = new Laji("lenkki"); 
    Laji punttisali = new Laji("punttisali"); 
    lenkki.rekisteroi(); 
    punttisali.rekisteroi(); 
    assertEquals("From: Lajit line: 26", 0, lajitX.getLkm()); 
    lajitX.lisaa(lenkki); 
    lajitX.lisaa(punttisali); 
    assertEquals("From: Lajit line: 29", 2, lajitX.getLkm()); 
    assertEquals("From: Lajit line: 30", lenkki, lajitX.getLaji(0)); 
    assertEquals("From: Lajit line: 31", punttisali, lajitX.getLaji(1)); 
  } // Generated by ComTest END
}