package luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.27 08:55:32 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi64 */
  @Test
  public void testRekisteroi64() {    // Pvm: 64
    Pvm tammi = new Pvm(11,1,2021); 
    Pvm loka = new Pvm(13,10,2021); 
    assertEquals("From: Pvm line: 67", 0, tammi.getTunnusNro()); 
    assertEquals("From: Pvm line: 68", 0, loka.getTunnusNro()); 
    tammi.rekisteroi(); 
    loka.rekisteroi(); 
    assertEquals("From: Pvm line: 71", 2, loka.getTunnusNro()); 
    loka.toString().equals("13.10.2021"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse162 */
  @Test
  public void testParse162() {    // Pvm: 162
    Pvm pvm = new Pvm(); 
    pvm.parse("1.1.2020"); 
    pvm.rekisteroi(); 
    assertEquals("From: Pvm line: 166", 3, pvm.getTunnusNro()); 
    pvm.getPaivays().equals("1.1.2020"); 
  } // Generated by ComTest END
}