package luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.29 11:49:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi63 */
  @Test
  public void testRekisteroi63() {    // Pvm: 63
    Pvm tammi = new Pvm(11,1,2021); 
    Pvm loka = new Pvm(13,10,2021); 
    assertEquals("From: Pvm line: 66", 0, tammi.getTunnusNro()); 
    assertEquals("From: Pvm line: 67", 0, loka.getTunnusNro()); 
    tammi.rekisteroi(); 
    loka.rekisteroi(); 
    assertEquals("From: Pvm line: 70", 2, loka.getTunnusNro()); 
    loka.toString().equals("13.10.2021"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse161 */
  @Test
  public void testParse161() {    // Pvm: 161
    Pvm pvm = new Pvm(); 
    pvm.parse("1.1.2020"); 
    pvm.rekisteroi(); 
    assertEquals("From: Pvm line: 165", 3, pvm.getTunnusNro()); 
    pvm.getPaivays().equals("1.1.2020"); 
  } // Generated by ComTest END
}