package luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 13:01:26 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmtTest {



  // Generated by ComTest BEGIN
  /** testLisaa19 */
  @Test
  public void testLisaa19() {    // Pvmt: 19
    Pvmt paivamaaratX = new Pvmt(); 
    Pvm paiva11 = new Pvm(1,1,1); 
    Pvm paiva22 = new Pvm(); 
    paiva11.rekisteroi(); 
    paiva22.rekisteroi(); 
    assertEquals("From: Pvmt line: 25", 0, paivamaaratX.getPvmLkm()); 
    paivamaaratX.lisaa(paiva11); 
    paivamaaratX.lisaa(paiva22); 
    assertEquals("From: Pvmt line: 28", 2, paivamaaratX.getPvmLkm()); 
    assertEquals("From: Pvmt line: 29", paiva11, paivamaaratX.annaPvm(1)); 
    assertEquals("From: Pvmt line: 30", paiva22, paivamaaratX.annaPvm(2)); 
  } // Generated by ComTest END
}