package luokat.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.15 12:23:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmtTest {



  // Generated by ComTest BEGIN
  /** testLisaa36 */
  @Test
  public void testLisaa36() {    // Pvmt: 36
    Pvmt paivamaaratX = new Pvmt(); 
    Pvm paiva11 = new Pvm(1,1,1); 
    Pvm paiva22 = new Pvm(); 
    paiva11.rekisteroi(); 
    paiva22.rekisteroi(); 
    assertEquals("From: Pvmt line: 42", 0, paivamaaratX.getPvmLkm()); 
    paivamaaratX.lisaa(paiva11); 
    paivamaaratX.lisaa(paiva22); 
    assertEquals("From: Pvmt line: 45", 2, paivamaaratX.getPvmLkm()); 
    assertEquals("From: Pvmt line: 46", paiva11, paivamaaratX.annaPvm(paiva11.getTunnusNro())); 
    assertEquals("From: Pvmt line: 47", paiva22, paivamaaratX.annaPvm(paiva22.getTunnusNro())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta104 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta104() throws SailoException {    // Pvmt: 104
    Pvmt pvmt = new Pvmt(); 
    Pvm paiva1 = new Pvm(); 
    Pvm paiva2 = new Pvm(); 
    paiva1.taytaTiedot(); 
    paiva2.taytaTiedot(); 
    paiva1.rekisteroi(); 
    paiva2.rekisteroi(); 
    String hakemisto = "testikayttaja"; 
    String tiedNimi = hakemisto+"/pvmt"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    pvmt.lueTiedostosta(tiedNimi); 
    fail("Pvmt: 122 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    pvmt.lisaa(paiva1); 
    pvmt.lisaa(paiva2); 
    pvmt.tallenna(); 
    pvmt = new Pvmt();  // Poistetaan vanhat luomalla uusi
    pvmt.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    Iterator<Pvm> i = pvmt.iterator(); 
    i.next().equals(paiva1); 
    i.next().equals(paiva2); 
    assertEquals("From: Pvmt line: 131", false, i.hasNext()); 
    pvmt.lisaa(paiva2); 
    pvmt.tallenna(); 
    assertEquals("From: Pvmt line: 134", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Pvmt line: 136", true, fbak.delete()); 
    assertEquals("From: Pvmt line: 137", true, dir.delete()); 
  } // Generated by ComTest END
}