package luokat.test;
// Generated by ComTest BEGIN
import luokat.*;
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.29 11:48:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UrheilutTest {



  // Generated by ComTest BEGIN
  /** testLisaa45 */
  @Test
  public void testLisaa45() {    // Urheilut: 45
    Urheilut urheilutX = new Urheilut(); 
    Urheilu sali1 = new Urheilu(1); 
    urheilutX.lisaa(sali1); 
    Urheilu lenkki1 = new Urheilu(2); 
    Urheilu lenkki2 = new Urheilu(2); 
    urheilutX.lisaa(lenkki1); 
    urheilutX.lisaa(lenkki2); 
    Urheilu sali2 = new Urheilu(1); 
    urheilutX.lisaa(sali2); 
    Urheilu latka1 = new Urheilu(2); 
    urheilutX.lisaa(latka1); 
    Iterator<Urheilu> i2=urheilutX.iterator(); 
    i2.next().equals(sali1); 
    i2.next().equals(lenkki1); 
    i2.next().equals(lenkki2); 
    i2.next().equals(sali2); 
    i2.next().equals(latka1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta89 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta89() throws SailoException {    // Urheilut: 89
    Urheilut urheilut = new Urheilut(); 
    Urheilu urh1 = new Urheilu(); 
    Urheilu urh2 = new Urheilu(); 
    urh1.taytaTiedot(); 
    urh2.taytaTiedot(); 
    urh1.rekisteroi(); 
    urh2.rekisteroi(); 
    String hakemisto = "testikayttaja"; 
    String tiedNimi = hakemisto+"/urheilut"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    urheilut.lueTiedostosta(tiedNimi); 
    fail("Urheilut: 107 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    urheilut.lisaa(urh1); 
    urheilut.lisaa(urh2); 
    urheilut.tallenna(); 
    urheilut = new Urheilut();  // Poistetaan vanhat luomalla uusi
    urheilut.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    Iterator<Urheilu> i = urheilut.iterator(); 
    i.next().toString().equals(urh1.toString()); 
    i.next().toString().equals(urh2.toString()); 
    assertEquals("From: Urheilut line: 116", false, i.hasNext()); 
    urheilut.lisaa(urh2); 
    urheilut.tallenna(); 
    assertEquals("From: Urheilut line: 119", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Urheilut line: 121", true, fbak.delete()); 
    assertEquals("From: Urheilut line: 122", true, dir.delete()); 
  } // Generated by ComTest END
}