package luokat.test;
// Generated by ComTest BEGIN
import luokat.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 13:32:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UrheilutTest {



  // Generated by ComTest BEGIN
  /** testLisaa40 */
  @Test
  public void testLisaa40() {    // Urheilut: 40
    Urheilut urheilutX = new Urheilut(); 
    Urheilu sali1 = new Urheilu(1); 
    urheilutX.lisaa(sali1); 
    Urheilu lenkki1 = new Urheilu(2); 
    Urheilu lenkki2 = new Urheilu(2); 
    urheilutX.lisaa(lenkki1); 
    urheilutX.lisaa(lenkki2); 
    Urheilu sali2 = new Urheilu(1); 
    urheilutX.lisaa(sali2); 
    Urheilu latka1 = new Urheilu(2); 
    urheilutX.lisaa(latka1); 
    Iterator<Urheilu> i2=urheilutX.iterator(); 
    assertEquals("From: Urheilut line: 57", sali1, i2.next()); 
    assertEquals("From: Urheilut line: 58", lenkki1, i2.next()); 
    assertEquals("From: Urheilut line: 59", lenkki2, i2.next()); 
    assertEquals("From: Urheilut line: 60", sali2, i2.next()); 
    assertEquals("From: Urheilut line: 61", latka1, i2.next()); 
  } // Generated by ComTest END
}