package luokat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import luokat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 13:41:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UrheiluTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi55 */
  @Test
  public void testRekisteroi55() {    // Urheilu: 55
    Urheilu gymi1 = new Urheilu(); 
    assertEquals("From: Urheilu line: 57", 0, gymi1.getTunnusNro()); 
    gymi1.rekisteroi(); 
    Urheilu kaljakellunta1 = new Urheilu(); 
    kaljakellunta1.rekisteroi(); 
    int n1 = gymi1.getTunnusNro(); 
    int n2 = kaljakellunta1.getTunnusNro(); 
    assertEquals("From: Urheilu line: 63", n2-1, n1); 
  } // Generated by ComTest END
}